"""v1

Revision ID: e7efdf231461
Revises: 
Create Date: 2025-03-14 18:13:04.821402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7efdf231461'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deck',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('deck', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deck_name'), ['name'], unique=False)

    op.create_table('flashcard',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('front', sa.String(), nullable=False),
    sa.Column('back', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('flashcard', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_flashcard_back'), ['back'], unique=False)
        batch_op.create_index(batch_op.f('ix_flashcard_front'), ['front'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    with op.batch_alter_table('flashcard', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_flashcard_front'))
        batch_op.drop_index(batch_op.f('ix_flashcard_back'))

    op.drop_table('flashcard')
    with op.batch_alter_table('deck', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deck_name'))

    op.drop_table('deck')
    # ### end Alembic commands ###
